[build]
rustflags = ["-C", "symbol-mangling-version=v0"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-cpu=x86-64-v2"]

# For flamegraphs
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
