name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install repro-env
      run: |
        wget 'https://github.com/kpcyrd/repro-env/releases/download/v0.4.0/repro-env'
        echo 'e331825a19d41a5ad4dd7c1ce7a810eccbb9eb8945c3fc78abe9f040df8c1204  repro-env' | sha256sum -c -
        sudo install -m755 repro-env -t /usr/bin

    # - run: rustup toolchain install stable --profile minimal
    # - uses: Swatinem/rust-cache@v2

    - name: Build
      run: repro-env build -- cargo build --verbose

    - name: Run tests
      run: repro-env build -- cargo test --verbose
