name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: default-runner

    steps:
    - uses: actions/checkout@v4

    - name: Install rustup
      run: wget -O - https://sh.rustup.rs | sh -s -- --profile minimal

    - uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test
