name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: never

jobs:
  test:
    runs-on: dind-small
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-22.04@sha256:e451382a9fe2bb34d253dfdaea49886be285526be9027e819ddbbdff5fcca799

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get -y install protobuf-compiler

      - name: Run all unit and integration tests
        run: |
          ./run-tests.sh
