name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: never
  GH_TOKEN: ${{ github.token }}

defaults:
  run:
    shell: bash

jobs:
  test:
    permissions:
      contents: write

    runs-on:
      - namespace-profile-ubuntu-24-04-big

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6

      - name: Install deps
        run: sudo apt-get update && sudo apt-get -y install protobuf-compiler && cargo install cargo-all-features

      - name: Run all unit and integration tests
        run: |
          ./run-tests.sh
