name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: bazel-runner-large

    steps:
    - uses: actions/checkout@v4

    - run: rustup toolchain install stable --profile minimal

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test
