name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: never
  GH_TOKEN: ${{ github.token }}

defaults:
  run:
    shell: bash

jobs:
  test:
    permissions:
      contents: write

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install repro-env
        run: |
          wget 'https://github.com/kpcyrd/repro-env/releases/download/v0.4.5/repro-env'
          echo 'd6a52bc7cfce4ff2e20dcdd01daf83968429f03f225178ef7f687f286a0d0ab4  repro-env' | sha256sum -c -
          sudo install -m755 repro-env -t /usr/bin

      - name: Install deps
        run: sudo apt-get -y install catatonit && cargo install cargo-all-features

      - name: Run all unit and integration tests
        run: |
          ./run-tests.sh && cargo clean && rm -rf target

      - name: Build using repro-env
        run: repro-env build -- cargo build --all-features --target x86_64-unknown-linux-musl --bin ic-gateway
