name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: never

jobs:
  test:
    runs-on: dind-small
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2

    - name: Install protoc
      run: sudo apt-get update && sudo apt-get -y install protobuf-compiler

    - name: Run tests
      run: cargo test
