name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: never
  GH_TOKEN: ${{ github.token }}

defaults:
  run:
    shell: bash

jobs:
  test:
    permissions:
      contents: write

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6

      - name: Install repro-env
        run: |
          wget 'https://github.com/kpcyrd/repro-env/releases/download/v0.4.4/repro-env'
          echo 'eaae57fbb51f6f802cb1c5ea4c07588feb18f8f533d7175b3cde599a974bb0d3  repro-env' | sha256sum -c -
          sudo install -m755 repro-env -t /usr/bin

      - name: Install deps
        run: sudo apt-get update && sudo apt-get -y install protobuf-compiler && cargo install cargo-all-features

      - name: Run all unit and integration tests
        run: |
          ./run-tests.sh

      - name: Build using repro-env
        run: repro-env build --env CFLAGS="-fno-link-libatomic" -- cargo build --features sev-snp --target x86_64-unknown-linux-musl
