name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: never

jobs:
  test:
    runs-on: dind-small
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-22.04@sha256:baeacfa8e05a4402c2e17d8a495dadbb7a6062a8ae44eef7c22424d617c53373

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get -y install protobuf-compiler

      - name: Run tests
        run: cargo test
